package jp.cloudear.test.db;

import java.util.List;
import jp.cloudear.test.db.Test3;
import jp.cloudear.test.db.Test3Example;
import org.apache.ibatis.annotations.Param;

public interface Test3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    long countByExample(Test3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int deleteByExample(Test3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int deleteByPrimaryKey(Long rssInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int insert(Test3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int insertSelective(Test3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    List<Test3> selectByExample(Test3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    Test3 selectByPrimaryKey(Long rssInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int updateByExampleSelective(@Param("record") Test3 record, @Param("example") Test3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int updateByExample(@Param("record") Test3 record, @Param("example") Test3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int updateByPrimaryKeySelective(Test3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST3
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    int updateByPrimaryKey(Test3 record);
}