package jp.cloudear.test.db;

import java.util.Date;

public class Test3 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.RSS_INFO_ID
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Long rssInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.RSS_URL
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private String rssUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.TITLE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.CREATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.UPDATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.VERSION
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.ERR_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Short errFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST3.INVALID_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    private Short invalidFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.RSS_INFO_ID
     *
     * @return the value of TEST.TEST3.RSS_INFO_ID
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Long getRssInfoId() {
        return rssInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.RSS_INFO_ID
     *
     * @param rssInfoId the value for TEST.TEST3.RSS_INFO_ID
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setRssInfoId(Long rssInfoId) {
        this.rssInfoId = rssInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.RSS_URL
     *
     * @return the value of TEST.TEST3.RSS_URL
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public String getRssUrl() {
        return rssUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.RSS_URL
     *
     * @param rssUrl the value for TEST.TEST3.RSS_URL
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setRssUrl(String rssUrl) {
        this.rssUrl = rssUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.TITLE
     *
     * @return the value of TEST.TEST3.TITLE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.TITLE
     *
     * @param title the value for TEST.TEST3.TITLE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.CREATE_DATE
     *
     * @return the value of TEST.TEST3.CREATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.CREATE_DATE
     *
     * @param createDate the value for TEST.TEST3.CREATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.UPDATE_DATE
     *
     * @return the value of TEST.TEST3.UPDATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.UPDATE_DATE
     *
     * @param updateDate the value for TEST.TEST3.UPDATE_DATE
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.VERSION
     *
     * @return the value of TEST.TEST3.VERSION
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.VERSION
     *
     * @param version the value for TEST.TEST3.VERSION
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.ERR_FLG
     *
     * @return the value of TEST.TEST3.ERR_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Short getErrFlg() {
        return errFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.ERR_FLG
     *
     * @param errFlg the value for TEST.TEST3.ERR_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setErrFlg(Short errFlg) {
        this.errFlg = errFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST3.INVALID_FLG
     *
     * @return the value of TEST.TEST3.INVALID_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public Short getInvalidFlg() {
        return invalidFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST3.INVALID_FLG
     *
     * @param invalidFlg the value for TEST.TEST3.INVALID_FLG
     *
     * @mbg.generated Sat Feb 11 21:08:46 JST 2017
     */
    public void setInvalidFlg(Short invalidFlg) {
        this.invalidFlg = invalidFlg;
    }
}