package jp.cloudear.test.db2;

import java.math.BigDecimal;
import java.util.Date;

public class Test6 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.RSS_INFO_ID
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private BigDecimal rssInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.RSS_URL
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private String rssUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.TITLE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.CREATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.UPDATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.VERSION
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private BigDecimal version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.ERR_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private Short errFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.TEST6.INVALID_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    private Short invalidFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.RSS_INFO_ID
     *
     * @return the value of SYSTEM.TEST6.RSS_INFO_ID
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public BigDecimal getRssInfoId() {
        return rssInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.RSS_INFO_ID
     *
     * @param rssInfoId the value for SYSTEM.TEST6.RSS_INFO_ID
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setRssInfoId(BigDecimal rssInfoId) {
        this.rssInfoId = rssInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.RSS_URL
     *
     * @return the value of SYSTEM.TEST6.RSS_URL
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public String getRssUrl() {
        return rssUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.RSS_URL
     *
     * @param rssUrl the value for SYSTEM.TEST6.RSS_URL
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setRssUrl(String rssUrl) {
        this.rssUrl = rssUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.TITLE
     *
     * @return the value of SYSTEM.TEST6.TITLE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.TITLE
     *
     * @param title the value for SYSTEM.TEST6.TITLE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.CREATE_DATE
     *
     * @return the value of SYSTEM.TEST6.CREATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.CREATE_DATE
     *
     * @param createDate the value for SYSTEM.TEST6.CREATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.UPDATE_DATE
     *
     * @return the value of SYSTEM.TEST6.UPDATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.UPDATE_DATE
     *
     * @param updateDate the value for SYSTEM.TEST6.UPDATE_DATE
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.VERSION
     *
     * @return the value of SYSTEM.TEST6.VERSION
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.VERSION
     *
     * @param version the value for SYSTEM.TEST6.VERSION
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.ERR_FLG
     *
     * @return the value of SYSTEM.TEST6.ERR_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public Short getErrFlg() {
        return errFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.ERR_FLG
     *
     * @param errFlg the value for SYSTEM.TEST6.ERR_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setErrFlg(Short errFlg) {
        this.errFlg = errFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.TEST6.INVALID_FLG
     *
     * @return the value of SYSTEM.TEST6.INVALID_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public Short getInvalidFlg() {
        return invalidFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.TEST6.INVALID_FLG
     *
     * @param invalidFlg the value for SYSTEM.TEST6.INVALID_FLG
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    public void setInvalidFlg(Short invalidFlg) {
        this.invalidFlg = invalidFlg;
    }
}