package jp.cloudear.test.db2;

import java.util.List;
import jp.cloudear.test.db2.Test6;
import jp.cloudear.test.db2.Test6Example;
import org.apache.ibatis.annotations.Param;

public interface Test6Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    long countByExample(Test6Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    int deleteByExample(Test6Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    int insert(Test6 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    int insertSelective(Test6 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    List<Test6> selectByExample(Test6Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    int updateByExampleSelective(@Param("record") Test6 record, @Param("example") Test6Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.TEST6
     *
     * @mbg.generated Sun Feb 12 17:57:05 JST 2017
     */
    int updateByExample(@Param("record") Test6 record, @Param("example") Test6Example example);
}